### PR TITLE
Support for optional port and change the way upload directories are created

### PR DESCRIPTION
**Pull request by RustyKnight**
# Optional port
Add support to supply a option port (-t/port) for the target server

May system operators will not allow "common" ports to be used and require the port number to be "randomised" for security

```
sftp_upload(
    server_url: "...",
    server_user: "...",
    server_key: "#{Dir.home}/...",
    target_dir: "...", 
    file_paths:["...", "..."],
    port: "12345"
)
```

# Change target directory handling
* Remove appending "home/{user}" to the target path
  * The "target" location should be fully configured by the user as it does not support "chroot jail" configurations (and I spend more then a few hours trying to diagnose why my tests were failing)
  * The original behaviour "could" be supplied as optional flag if it's still desired
* Create each level of the target path as a seperate operation, as `mkdir` doesn't seem to perform this operation and part or the whole target location may not already exist of the server

### CODE REVIEW

**Comment by oklimberg** [comment]
Hi Shane,

the additional option to provide a custom port sounds good and I will happily apply this, but at least the existing tests should still pass with your changes. 
I am currently adjusting them accordingly.

Is there any reason, you are masking the server port in the overview when printing all parameters?

**Comment by oklimberg** [comment]
@RustyKnight 
Please let me know, if my changes (most important, changing the parameter name from 'port' to 'server_port') still work for your setup. If so, i will merge youre request and publish a new version

**Comment by RustyKnight** [comment]
@oklimberg No, there is no reason to print the port name, other then for my own sanity checking.

I have no issue with changing the parameter name, it makes sense.

If I’d had more time I probably would have included a flag, something like “prefix_user_home” which defaulted to true, which would have continued to operate as per your original design

Let me know if you’d like me to include it, it’s “slightly” annoying for my implementation but I respect that you and others probably already have setups which rely on this feature

**Comment by oklimberg** [comment]
Printing the port is totally fine, but your current implementation will hide the actual value in the overview. 
I will change this before merging tomorrow. 

Further more, the changes in your master should be mostly backwards compatible. 
Absolute paths can now be provided and relative paths will be relative to the folder the user is located after login.

Glad this plugin is useful for anybody else other than me and thanks for contributing.

**Comment by RustyKnight** [comment]
Thanks for considering my updates.  You are right, I should have made more consideration to backwards compatibility, it was short sighted on my part.

I apologise, as my fast lane is basic and my ruby is worse, so I took quite a bit of my effort to dig around and figure out how it all worked.  Missing the port option was part of a copy and paste process, as I didn't originally intended to create a pull request, again, my bad.

I like the changes you've made and appreciate taking the time to incorporate them, it will save me a tone of time!

**Comment by oklimberg** [comment]
this changes will also fix #1

**Pull request merged**
